import { db, fb } from './firebase.js';

const $ = id => document.getElementById(id);
const chantiersCol = fb.collection(db, 'chantiers');
const agentsCol = fb.collection(db, 'agents');
let data = [];
let agents = {};

function norm(v){return(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function agentKey(v){return norm(v).replace(/\s+/g,' ')}
function agentsOf(row){return[row.poubelle,row.menage,row.gardiennage].filter(Boolean)}
function unique(arr){return[...new Set(arr.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fr'))}
function escapeHtml(s){return(s||'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(msg){const t=$('toast');t.textContent=msg;t.style.display='block';setTimeout(()=>t.style.display='none',2300)}
function getPhone(agent){const a=agents[agentKey(agent)];return a?.phone||''}
function getAgentName(agent){const a=agents[agentKey(agent)];return a?.name||agent}
function phoneHtml(agent){const p=getPhone(agent);if(!agent)return'';const display=getAgentName(agent);return p?`<div class="phone"><strong>${escapeHtml(display)}</strong><br><a class="call" href="tel:${p.replace(/\s/g,'')}">📞 ${escapeHtml(p)}</a></div>`:`<div><strong>${escapeHtml(display)}</strong><br><span class="small">Numéro non renseigné</span></div>`}
function phonesForRow(row){return agentsOf(row).map(phoneHtml).join('<hr style="border:0;border-top:1px solid #eee">')}
function fillFilters(){const currentC=$('clientFilter').value,currentA=$('agentFilter').value;const clients=unique(data.map(r=>r.client));const agentNames=unique([...data.flatMap(agentsOf),...Object.values(agents).map(a=>a.name)]);$('clientFilter').innerHTML='<option value="">Tous</option>'+clients.map(v=>`<option ${v===currentC?'selected':''}>${escapeHtml(v)}</option>`).join('');$('agentFilter').innerHTML='<option value="">Tous</option>'+agentNames.map(v=>`<option ${v===currentA?'selected':''}>${escapeHtml(v)}</option>`).join('');$('kClients').textContent=clients.length;$('kAgents').textContent=Object.keys(agents).length}
function filtered(){const q=norm($('search').value),c=$('clientFilter').value,a=$('agentFilter').value,svc=$('serviceFilter').value;return data.filter(r=>{const phones=agentsOf(r).map(getPhone).join(' ');const blob=norm([r.chantier,r.cp,r.poubelle,r.menage,r.gardiennage,r.client,phones].join(' '));if(q&&!blob.includes(q))return false;if(c&&r.client!==c)return false;if(a&&!agentsOf(r).map(agentKey).includes(agentKey(a)))return false;if(svc&&!r[svc])return false;return true})}
function renderAgents(){const names=unique([...Object.values(agents).map(a=>a.name),...data.flatMap(agentsOf)]);$('agentList').innerHTML=names.map(name=>{const key=agentKey(name);const a=agents[key]||{name,phone:''};return `<div class="agent-pill"><strong>${escapeHtml(a.name)}</strong><div class="small">${a.phone?escapeHtml(a.phone):'Numéro non renseigné'}</div><div class="actions" style="margin-top:6px"><button class="secondary" onclick="editAgent('${key}')">Modifier</button><button class="danger" onclick="deleteAgent('${key}')">Supprimer agent</button></div></div>`}).join('')||'<div class="small">Aucun agent.</div>'}
function render(){fillFilters();renderAgents();const rows=filtered();$('kTotal').textContent=data.length;$('kVisible').textContent=rows.length;$('tbody').innerHTML=rows.map(r=>`<tr><td><strong>${escapeHtml(r.chantier)}</strong><div class="small">Source: ${escapeHtml(r.source||'Ajout manuel')}</div></td><td>${escapeHtml(r.cp)}</td><td>${escapeHtml(r.poubelle)}</td><td>${escapeHtml(r.menage)}</td><td>${escapeHtml(r.gardiennage)}</td><td>${phonesForRow(r)}</td><td><span class="badge">${escapeHtml(r.client)}</span></td><td><button class="secondary" onclick="editRow('${r.id}')">Modifier</button> <button class="danger" onclick="delRow('${r.id}')">Supprimer</button></td></tr>`).join('')||'<tr><td colspan="8">Aucun résultat</td></tr>'}

fb.onSnapshot(chantiersCol, snap=>{data=snap.docs.map(d=>({id:d.id,...d.data()}));data.sort((a,b)=>(a.chantier||'').localeCompare(b.chantier||'','fr'));render();}, err=>alert('Erreur Firebase chantiers: '+err.message));
fb.onSnapshot(agentsCol, snap=>{agents={};snap.docs.forEach(d=>{agents[d.id]=d.data()});render();}, err=>alert('Erreur Firebase agents: '+err.message));

function openModal(row=null){$('modalTitle').textContent=row?'Modifier le chantier':'Ajouter un chantier';$('editId').value=row?.id||'';$('fChantier').value=row?.chantier||'';$('fCp').value=row?.cp||'';$('fPoubelle').value=row?.poubelle||'';$('fMenage').value=row?.menage||'';$('fGardiennage').value=row?.gardiennage||'';$('fClient').value=row?.client||'';$('modal').classList.add('open');$('fChantier').focus()}
function closeModal(){$('modal').classList.remove('open')}
window.editRow=id=>openModal(data.find(r=>r.id===id));
window.delRow=async id=>{if(confirm('Supprimer ce chantier ?')){await fb.deleteDoc(fb.doc(db,'chantiers',id));toast('Chantier supprimé')}};
window.editAgent=key=>{const a=agents[key];$('agentName').value=a?.name||key;$('agentPhone').value=a?.phone||'';$('agentName').focus()};
window.deleteAgent=async key=>{const a=agents[key];const nom=a?.name||key;const used=data.some(r=>agentsOf(r).map(agentKey).includes(key));let msg=`Supprimer l'agent ${nom} ?`+ (used?`\n\nAttention : il est encore affecté sur un ou plusieurs chantiers. Les chantiers garderont son nom, mais le numéro ne sera plus affiché.`:'');if(confirm(msg)){await fb.deleteDoc(fb.doc(db,'agents',key));toast('Agent supprimé')}};

$('saveAgentBtn').onclick=async()=>{const name=$('agentName').value.trim();const phone=$('agentPhone').value.trim();if(!name)return alert('Saisissez le nom de l’agent');await fb.setDoc(fb.doc(db,'agents',agentKey(name)),{name,phone,updatedAt:fb.serverTimestamp()});$('agentName').value='';$('agentPhone').value='';toast('Agent enregistré')};
$('addBtn').onclick=()=>openModal();$('cancelBtn').onclick=closeModal;$('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
$('saveBtn').onclick=async()=>{const id=$('editId').value;const row={chantier:$('fChantier').value.trim(),cp:$('fCp').value.trim(),poubelle:$('fPoubelle').value.trim(),menage:$('fMenage').value.trim(),gardiennage:$('fGardiennage').value.trim(),client:$('fClient').value.trim(),source:id?(data.find(r=>r.id===id)?.source||'Ajout manuel'):'Ajout manuel',updatedAt:fb.serverTimestamp()};if(!row.chantier)return alert('Saisissez le chantier / adresse');if(id){await fb.updateDoc(fb.doc(db,'chantiers',id),row);toast('Chantier modifié')}else{row.createdAt=fb.serverTimestamp();await fb.addDoc(chantiersCol,row);toast('Chantier ajouté')}closeModal()};
['search','clientFilter','agentFilter','serviceFilter'].forEach(id=>$(id).addEventListener('input',render));
$('importBtn').onclick=()=>$('importFile').click();
$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const buf=await file.arrayBuffer();let rows=[];if(file.name.toLowerCase().endsWith('.csv')||file.name.toLowerCase().endsWith('.txt')){const text=new TextDecoder('utf-8').decode(buf);rows=text.split(/\r?\n/).filter(Boolean).map(line=>line.split(/[;,\t]/));}else{const wb=XLSX.read(buf,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});}
const headers=(rows.shift()||[]).map(h=>norm(h));const idx=n=>headers.findIndex(h=>h.includes(n));const iCh=idx('adresse')>=0?idx('adresse'):idx('chantier');const iCp=idx('cp')>=0?idx('cp'):idx('ville');const iPou=idx('poubelle');const iMen=idx('menage');const iGar=idx('gardiennage');const iClient=idx('client');let count=0;const batch=fb.writeBatch(db);rows.forEach(r=>{const chantier=(r[iCh]||'').toString().trim();if(!chantier)return;const ref=fb.doc(chantiersCol);batch.set(ref,{chantier,cp:(r[iCp]||'').toString().trim(),poubelle:iPou>=0?(r[iPou]||'').toString().trim():'',menage:iMen>=0?(r[iMen]||'').toString().trim():'',gardiennage:iGar>=0?(r[iGar]||'').toString().trim():'',client:iClient>=0?(r[iClient]||'').toString().trim():'',source:'Import',createdAt:fb.serverTimestamp(),updatedAt:fb.serverTimestamp()});count++});await batch.commit();toast(count+' chantier(s) importé(s)');e.target.value=''};
$('exportBtn').onclick=()=>{const rows=[['Chantier','CP/Ville','Poubelle','Ménage','Gardiennage','Client'],...data.map(r=>[r.chantier,r.cp,r.poubelle,r.menage,r.gardiennage,r.client])];const csv=rows.map(l=>l.map(v=>'"'+String(v||'').replaceAll('"','""')+'"').join(';')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='listing_chantiers.csv';a.click();URL.revokeObjectURL(url)};
